logging:
  level:
    org:
      springframework: DEBUG
server:
  port: 9003
  
  
  
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:file:C:/data/user
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  application:
    name: USER-SERVICE
  
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
         defaultZone: http://localhost:8761/eureka
      
  instance:
    hostname: localhost
    
      
      